services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Indique à Docker de charger votre fichier .env manuel
    env_file:
      - .env
    environment:
      # On reconstruit l'URL pour Prisma en utilisant les variables du .env
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
    # S'assure que la DB est prête avant de lancer l'app
    depends_on:
      - db

volumes:
  db-data: